### ISSUE TITLE
Roadmap for 1.0

### ISSUE THREAD

**Issue by CAMongrel** [UnrealLightweightServer/ULS.Core#1]
There is no specific date for a 1.0 release and the roadmap is still growing.

- [x] #2
- [ ] #3
- [ ] #4
- [x] #5
- [x] #8
- [ ] #9
- [ ] #10
- [ ] #11
- [ ] Implement RPC calls with return values
- [x] Better support for reflection for RPCs on the client side (#8)
- [x] Support UE 5.0 final version
- [ ] Implement protocol awareness (reliable / unreliable data transfer)
- [ ] Investigate and implement USubsystem for ULS to make usage easier
- [ ] #12
